/**
 * apply_images.js
 * 
 * Reads image_mapping.json (generated by image_picker.html)
 * and patches every matching item.image field across all JSON data files.
 * 
 * Usage:
 *   1. In image_picker.html, select all your images and click "Export Mapping"
 *   2. Move the downloaded image_mapping.json into this project root folder
 *   3. Run: node apply_images.js
 */

const fs   = require('fs');
const path = require('path');

// ── Load mapping ──────────────────────────────────────────────────────────────
const mappingPath = path.join(__dirname, 'image_mapping.json');
if (!fs.existsSync(mappingPath)) {
    console.error('❌  image_mapping.json not found in project root.');
    console.error('   → Open image_picker.html, make your selections, and click "Export Mapping".');
    process.exit(1);
}
const mapping = JSON.parse(fs.readFileSync(mappingPath, 'utf-8'));
console.log(`\n📄  Loaded mapping with ${Object.keys(mapping).length} entries.\n`);

// ── Walk data files ───────────────────────────────────────────────────────────
const dataDir = path.join(__dirname, 'datasets', 'data');
const files   = fs.readdirSync(dataDir).filter(f => f.endsWith('.json'));

let totalPatched  = 0;
let totalSkipped  = 0;

files.forEach(file => {
    const filePath = path.join(dataDir, file);
    const raw = fs.readFileSync(filePath, 'utf-8').trim();
    if (!raw || raw === '{}') return;

    let parsed;
    try { parsed = JSON.parse(raw); }
    catch (e) { console.error(`⚠  Could not parse ${file}`); return; }

    const states = parsed.states || {};
    let fileChanged = false;

    Object.values(states).forEach(stateData => {
        (stateData.sections || []).forEach(section => {
            (section.items || []).forEach(item => {
                if (mapping[item.id]) {
                    const newUrl = mapping[item.id].url;
                    if (item.image !== newUrl) {
                        item.image = newUrl;
                        totalPatched++;
                        fileChanged = true;
                        console.log(`  ✅  ${file.padEnd(32)} → ${item.id} → URL set`);
                    }
                } else {
                    totalSkipped++;
                }
            });
        });
    });

    // Write back only if something changed
    if (fileChanged) {
        fs.writeFileSync(filePath, JSON.stringify(parsed, null, 4), 'utf-8');
    }
});

// ── Summary ───────────────────────────────────────────────────────────────────
console.log('\n' + '═'.repeat(54));
console.log(`  ✅  Patched   : ${totalPatched} item(s)`);
console.log(`  ⏭   Skipped   : ${totalSkipped} item(s) (no mapping entry)`);
console.log('═'.repeat(54) + '\n');
